#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Thiết_kế_màn_hình_đăng_nhập
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="qlsvc#")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertLopHoc(LopHoc instance);
    partial void UpdateLopHoc(LopHoc instance);
    partial void DeleteLopHoc(LopHoc instance);
    partial void InsertSinhVien(SinhVien instance);
    partial void UpdateSinhVien(SinhVien instance);
    partial void DeleteSinhVien(SinhVien instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::Thiết_kế_màn_hình_đăng_nhập.Properties.Settings.Default.qlsvc_ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<LopHoc> LopHocs
		{
			get
			{
				return this.GetTable<LopHoc>();
			}
		}
		
		public System.Data.Linq.Table<SinhVien> SinhViens
		{
			get
			{
				return this.GetTable<SinhVien>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LopHoc")]
	public partial class LopHoc : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _id;
		
		private string _ma_lop;
		
		private string _ten_lop;
		
		private string _ghi_chu;
		
		private EntitySet<SinhVien> _SinhViens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(string value);
    partial void OnidChanged();
    partial void Onma_lopChanging(string value);
    partial void Onma_lopChanged();
    partial void Onten_lopChanging(string value);
    partial void Onten_lopChanged();
    partial void Onghi_chuChanging(string value);
    partial void Onghi_chuChanged();
    #endregion
		
		public LopHoc()
		{
			this._SinhViens = new EntitySet<SinhVien>(new Action<SinhVien>(this.attach_SinhViens), new Action<SinhVien>(this.detach_SinhViens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma_lop", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string ma_lop
		{
			get
			{
				return this._ma_lop;
			}
			set
			{
				if ((this._ma_lop != value))
				{
					this.Onma_lopChanging(value);
					this.SendPropertyChanging();
					this._ma_lop = value;
					this.SendPropertyChanged("ma_lop");
					this.Onma_lopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten_lop", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string ten_lop
		{
			get
			{
				return this._ten_lop;
			}
			set
			{
				if ((this._ten_lop != value))
				{
					this.Onten_lopChanging(value);
					this.SendPropertyChanging();
					this._ten_lop = value;
					this.SendPropertyChanged("ten_lop");
					this.Onten_lopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ghi_chu", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string ghi_chu
		{
			get
			{
				return this._ghi_chu;
			}
			set
			{
				if ((this._ghi_chu != value))
				{
					this.Onghi_chuChanging(value);
					this.SendPropertyChanging();
					this._ghi_chu = value;
					this.SendPropertyChanged("ghi_chu");
					this.Onghi_chuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LopHoc_SinhVien", Storage="_SinhViens", ThisKey="ma_lop", OtherKey="ma_lop")]
		public EntitySet<SinhVien> SinhViens
		{
			get
			{
				return this._SinhViens;
			}
			set
			{
				this._SinhViens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_SinhViens(SinhVien entity)
		{
			this.SendPropertyChanging();
			entity.LopHoc = this;
		}
		
		private void detach_SinhViens(SinhVien entity)
		{
			this.SendPropertyChanging();
			entity.LopHoc = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SinhVien")]
	public partial class SinhVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ma_sv;
		
		private string _ho_ten;
		
		private System.Nullable<System.DateTime> _ngay_sinh;
		
		private string _gioi_tinh;
		
		private string _ma_lop;
		
		private EntityRef<LopHoc> _LopHoc;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onma_svChanging(string value);
    partial void Onma_svChanged();
    partial void Onho_tenChanging(string value);
    partial void Onho_tenChanged();
    partial void Onngay_sinhChanging(System.Nullable<System.DateTime> value);
    partial void Onngay_sinhChanged();
    partial void Ongioi_tinhChanging(string value);
    partial void Ongioi_tinhChanged();
    partial void Onma_lopChanging(string value);
    partial void Onma_lopChanged();
    #endregion
		
		public SinhVien()
		{
			this._LopHoc = default(EntityRef<LopHoc>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma_sv", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ma_sv
		{
			get
			{
				return this._ma_sv;
			}
			set
			{
				if ((this._ma_sv != value))
				{
					this.Onma_svChanging(value);
					this.SendPropertyChanging();
					this._ma_sv = value;
					this.SendPropertyChanged("ma_sv");
					this.Onma_svChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ho_ten", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string ho_ten
		{
			get
			{
				return this._ho_ten;
			}
			set
			{
				if ((this._ho_ten != value))
				{
					this.Onho_tenChanging(value);
					this.SendPropertyChanging();
					this._ho_ten = value;
					this.SendPropertyChanged("ho_ten");
					this.Onho_tenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngay_sinh", DbType="Date")]
		public System.Nullable<System.DateTime> ngay_sinh
		{
			get
			{
				return this._ngay_sinh;
			}
			set
			{
				if ((this._ngay_sinh != value))
				{
					this.Onngay_sinhChanging(value);
					this.SendPropertyChanging();
					this._ngay_sinh = value;
					this.SendPropertyChanged("ngay_sinh");
					this.Onngay_sinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioi_tinh", DbType="NVarChar(20) NOT NULL", CanBeNull=false)]
		public string gioi_tinh
		{
			get
			{
				return this._gioi_tinh;
			}
			set
			{
				if ((this._gioi_tinh != value))
				{
					this.Ongioi_tinhChanging(value);
					this.SendPropertyChanging();
					this._gioi_tinh = value;
					this.SendPropertyChanged("gioi_tinh");
					this.Ongioi_tinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma_lop", DbType="VarChar(20)")]
		public string ma_lop
		{
			get
			{
				return this._ma_lop;
			}
			set
			{
				if ((this._ma_lop != value))
				{
					if (this._LopHoc.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.Onma_lopChanging(value);
					this.SendPropertyChanging();
					this._ma_lop = value;
					this.SendPropertyChanged("ma_lop");
					this.Onma_lopChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LopHoc_SinhVien", Storage="_LopHoc", ThisKey="ma_lop", OtherKey="ma_lop", IsForeignKey=true, DeleteRule="SET NULL")]
		public LopHoc LopHoc
		{
			get
			{
				return this._LopHoc.Entity;
			}
			set
			{
				LopHoc previousValue = this._LopHoc.Entity;
				if (((previousValue != value) 
							|| (this._LopHoc.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LopHoc.Entity = null;
						previousValue.SinhViens.Remove(this);
					}
					this._LopHoc.Entity = value;
					if ((value != null))
					{
						value.SinhViens.Add(this);
						this._ma_lop = value.ma_lop;
					}
					else
					{
						this._ma_lop = default(string);
					}
					this.SendPropertyChanged("LopHoc");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
